FROM osrf/ros:noetic-desktop-full

# ========================================
# ========================================

# Install dependencies
# For Ubuntu 20.04 + Noetic
RUN apt-get install python3-catkin-tools python3-vcstool python3-osrf-pycommon
# system dep.
RUN apt-get install libglew-dev libopencv-dev libyaml-cpp-dev 
# Ceres dep.
RUN apt-get install libblas-dev liblapack-dev libsuitesparse-dev
